In [1]:
import xlrd 
import pandas as pd

In [2]:
wb = xlrd.open_workbook("xml_dump_in_XL.xlsx") 
sheet = wb.sheet_by_index(0)

In [3]:
res = len(wb.sheet_names()) 
res

7

In [4]:
wb.sheet_names()

['MRBTS', 'LNBTS', 'LNBTS-2', 'LNBTS-3', 'HW', 'PPTT', 'BTSSCL']

In [5]:
# xls = pd.read_excel('xml_dump_in_XL.xlsx', sheet_name = None)
# print(xls.keys())

In [6]:
# df = xls['MRBTS']
# df

In [7]:
sheet

In [8]:
sheet.cell_value(1, 1)
len(wb.sheet_names())

7

In [33]:
def fill_cols(d, tempd):
    for keys in d:
        try:
            if(tempd[keys]):
                d[keys] = d[keys].append({keys: tempd[keys]}, ignore_index = True)
        except:
            if(keys != 'Parameter' and keys != 'Value' and keys != 'Class'):
                d[keys] = d[keys].append({keys: 'NA'}, ignore_index = True)
    return d
        
d1 = {'a': pd.DataFrame(columns = ['a']), 'b': pd.DataFrame(columns = ['b']), 'c': pd.DataFrame(columns = ['c']), 'Parameter': pd.DataFrame(columns = ['Parameter']), 'Value': pd.DataFrame(columns = ['Value'])}
tempd1 = {'a': 1, 'b': 2}
fill_cols(d1, tempd1)['Value']

Empty DataFrame
Columns: [Value]
Index: []

In [36]:
l = [5, 6, 3, 3, 5, 5, 3]
col = {}
col['Class'] = pd.DataFrame(columns = ['Class'])

for i in range(len(wb.sheet_names())):
    sheet = wb.sheet_by_index(i)
    for j in range(l[i]):
        col[sheet.cell_value(1,j)] = pd.DataFrame(columns = [sheet.cell_value(1,j)])
    col['Parameter'] = pd.DataFrame(columns = ['Parameter'])
    col['Value'] = pd.DataFrame(columns = ['Value'])    
    
for i in range(len(wb.sheet_names())):
    sheet = wb.sheet_by_index(i)
    print('Sheet Number: ' + str(i))
    print('Sheet Name: ' + wb.sheet_names()[i])
    
    for j in range(2, sheet.nrows):
        print(str(j) + ' out of ' + str(sheet.nrows))
        tempcol = {}
        for k in range(l[i]):
            tempcol[sheet.cell_value(1, k)] = sheet.cell_value(j, k)
        
        for k in range(l[i], sheet.ncols):
#             print("Start")
            col = fill_cols(col, tempcol)
#             print("End")
            col['Parameter'] = col['Parameter'].append({'Parameter': sheet.cell_value(1,k)}, ignore_index = True)
            col['Value'] = col['Value'].append({'Value': sheet.cell_value(j,k)}, ignore_index = True)
            col['Class'] = col['Class'].append({'Class': wb.sheet_names()[i]}, ignore_index = True)

df = pd.DataFrame()
for keys in col:
    df = pd.concat((df, col[keys]), axis = 1)
    
df

Sheet Number: 0
Sheet Name: MRBTS
2 out of 651
3 out of 651
4 out of 651
5 out of 651
6 out of 651
7 out of 651
8 out of 651
9 out of 651
10 out of 651
11 out of 651
12 out of 651
13 out of 651
14 out of 651
15 out of 651
16 out of 651
17 out of 651
18 out of 651
19 out of 651
20 out of 651
21 out of 651
22 out of 651
23 out of 651
24 out of 651
25 out of 651
26 out of 651
27 out of 651
28 out of 651
29 out of 651
30 out of 651
31 out of 651
32 out of 651
33 out of 651
34 out of 651
35 out of 651
36 out of 651
37 out of 651
38 out of 651
39 out of 651
40 out of 651
41 out of 651
42 out of 651
43 out of 651
44 out of 651
45 out of 651
46 out of 651
47 out of 651
48 out of 651
49 out of 651
50 out of 651
51 out of 651
52 out of 651
53 out of 651
54 out of 651
55 out of 651
56 out of 651
57 out of 651
58 out of 651
59 out of 651
60 out of 651
61 out of 651
62 out of 651
63 out of 651
64 out of 651
65 out of 651
66 out of 651
67 out of 651
68 out of 651
69 out of 651
70 out of 651
71 out of 651
72 out of 651
73 out of 651
74 out of 651
75 out of 651
76 out of 651
77 out of 651
78 out of 651
79 out of 651
80 out of 651
81 out of 651
82 out of 651
83 out of 651
84 out of 651
85 out of 651
86 out of 651
87 out of 651
88 out of 651
89 out of 651
90 out of 651
91 out of 651
92 out of 651
93 out of 651
94 out of 651
95 out of 651
96 out of 651
97 out of 651
98 out of 651
99 out of 651
100 out of 651
101 out of 651
102 out of 651
103 out of 651
104 out of 651
105 out of 651
106 out of 651
107 out of 651
108 out of 651
109 out of 651
110 out of 651
111 out of 651
112 out of 651
113 out of 651
114 out of 651
115 out of 651
116 out of 651
117 out of 651
118 out of 651
119 out of 651
120 out of 651
121 out of 651
122 out of 651
123 out of 651
124 out of 651
125 out of 651
126 out of 651
127 out of 651
128 out of 651
129 out of 651
130 out of 651
131 out of 651
132 out of 651
133 out of 651
134 out of 651
135 out of 651
136 out of 651
137 out of 651
138 out of 651
139 out of 651
140 out of 651
141 out of 651
142 out of 651
143 out of 651
144 out of 651
145 out of 651
146 out of 651
147 out of 651
148 out of 651
149 out of 651
150 out of 651
151 out of 651
152 out of 651
153 out of 651
154 out of 651
155 out of 651
156 out of 651
157 out of 651
158 out of 651
159 out of 651
160 out of 651
161 out of 651
162 out of 651
163 out of 651
164 out of 651
165 out of 651
166 out of 651
167 out of 651
168 out of 651
169 out of 651
170 out of 651
171 out of 651
172 out of 651
173 out of 651
174 out of 651
175 out of 651
176 out of 651
177 out of 651
178 out of 651
179 out of 651
180 out of 651
181 out of 651
182 out of 651
183 out of 651
184 out of 651
185 out of 651
186 out of 651
187 out of 651
188 out of 651
189 out of 651
190 out of 651
191 out of 651
192 out of 651
193 out of 651
194 out of 651
195 out of 651
196 out of 651
197 out of 651
198 out of 651
199 out of 651
200 out of 651
201 out of 651
202 out of 651
203 out of 651
204 out of 651
205 out of 651
206 out of 651
207 out of 651
208 out of 651
209 out of 651
210 out of 651
211 out of 651
212 out of 651
213 out of 651
214 out of 651
215 out of 651
216 out of 651
217 out of 651
218 out of 651
219 out of 651
220 out of 651
221 out of 651
222 out of 651
223 out of 651
224 out of 651
225 out of 651
226 out of 651
227 out of 651
228 out of 651
229 out of 651
230 out of 651
231 out of 651
232 out of 651
233 out of 651
234 out of 651
235 out of 651
236 out of 651
237 out of 651
238 out of 651
239 out of 651
240 out of 651
241 out of 651
242 out of 651
243 out of 651
244 out of 651
245 out of 651
246 out of 651
247 out of 651
248 out of 651
249 out of 651
250 out of 651
251 out of 651
252 out of 651
253 out of 651
254 out of 651
255 out of 651
256 out of 651
257 out of 651
258 out of 651
259 out of 651
260 out of 651
261 out of 651
262 out of 651
263 out of 651
264 out of 651
265 out of 651
266 out of 651
267 out of 651
268 out of 651
269 out of 651
270 out of 651
271 out of 651
272 out of 651
273 out of 651
274 out of 651
275 out of 651
276 out of 651
277 out of 651
278 out of 651
279 out of 651
280 out of 651
281 out of 651
282 out of 651
283 out of 651
284 out of 651
285 out of 651
286 out of 651
287 out of 651
288 out of 651
289 out of 651
290 out of 651
291 out of 651
292 out of 651
293 out of 651
294 out of 651
295 out of 651
296 out of 651
297 out of 651
298 out of 651
299 out of 651
300 out of 651
301 out of 651
302 out of 651
303 out of 651
304 out of 651
305 out of 651
306 out of 651
307 out of 651
308 out of 651
309 out of 651
310 out of 651
311 out of 651
312 out of 651
313 out of 651
314 out of 651
315 out of 651
316 out of 651
317 out of 651
318 out of 651
319 out of 651
320 out of 651
321 out of 651
322 out of 651
323 out of 651
324 out of 651
325 out of 651
326 out of 651
327 out of 651
328 out of 651
329 out of 651
330 out of 651
331 out of 651
332 out of 651
333 out of 651
334 out of 651
335 out of 651
336 out of 651
337 out of 651
338 out of 651
339 out of 651
340 out of 651
341 out of 651
342 out of 651
343 out of 651
344 out of 651
345 out of 651
346 out of 651
347 out of 651
348 out of 651
349 out of 651
350 out of 651
351 out of 651
352 out of 651
353 out of 651
354 out of 651
355 out of 651
356 out of 651
357 out of 651
358 out of 651
359 out of 651
360 out of 651
361 out of 651
362 out of 651
363 out of 651
364 out of 651
365 out of 651
366 out of 651
367 out of 651
368 out of 651
369 out of 651
370 out of 651
371 out of 651
372 out of 651
373 out of 651
374 out of 651
375 out of 651
376 out of 651
377 out of 651
378 out of 651
379 out of 651
380 out of 651
381 out of 651
382 out of 651
383 out of 651
384 out of 651
385 out of 651
386 out of 651
387 out of 651
388 out of 651
389 out of 651
390 out of 651
391 out of 651
392 out of 651
393 out of 651
394 out of 651
395 out of 651
396 out of 651
397 out of 651
398 out of 651
399 out of 651
400 out of 651
401 out of 651
402 out of 651
403 out of 651
404 out of 651
405 out of 651
406 out of 651
407 out of 651
408 out of 651
409 out of 651
410 out of 651
411 out of 651
412 out of 651
413 out of 651
414 out of 651
415 out of 651
416 out of 651
417 out of 651
418 out of 651
419 out of 651
420 out of 651
421 out of 651
422 out of 651
423 out of 651
424 out of 651
425 out of 651
426 out of 651
427 out of 651
428 out of 651
429 out of 651
430 out of 651
431 out of 651
432 out of 651
433 out of 651
434 out of 651
435 out of 651
436 out of 651
437 out of 651
438 out of 651
439 out of 651
440 out of 651
441 out of 651
442 out of 651
443 out of 651
444 out of 651
445 out of 651
446 out of 651
447 out of 651
448 out of 651
449 out of 651
450 out of 651
451 out of 651
452 out of 651
453 out of 651
454 out of 651
455 out of 651
456 out of 651
457 out of 651
458 out of 651
459 out of 651
460 out of 651
461 out of 651
462 out of 651
463 out of 651
464 out of 651
465 out of 651
466 out of 651
467 out of 651
468 out of 651
469 out of 651
470 out of 651
471 out of 651
472 out of 651
473 out of 651
474 out of 651
475 out of 651
476 out of 651
477 out of 651
478 out of 651
479 out of 651
480 out of 651
481 out of 651
482 out of 651
483 out of 651
484 out of 651
485 out of 651
486 out of 651
487 out of 651
488 out of 651
489 out of 651
490 out of 651
491 out of 651
492 out of 651
493 out of 651
494 out of 651
495 out of 651
496 out of 651
497 out of 651
498 out of 651
499 out of 651
500 out of 651
501 out of 651
502 out of 651
503 out of 651
504 out of 651
505 out of 651
506 out of 651
507 out of 651
508 out of 651
509 out of 651
510 out of 651
511 out of 651
512 out of 651
513 out of 651
514 out of 651
515 out of 651
516 out of 651
517 out of 651
518 out of 651
519 out of 651
520 out of 651
521 out of 651
522 out of 651
523 out of 651
524 out of 651
525 out of 651
526 out of 651
527 out of 651
528 out of 651
529 out of 651
530 out of 651
531 out of 651
532 out of 651
533 out of 651
534 out of 651
535 out of 651
536 out of 651
537 out of 651
538 out of 651
539 out of 651
540 out of 651
541 out of 651
542 out of 651
543 out of 651
544 out of 651
545 out of 651
546 out of 651
547 out of 651
548 out of 651
549 out of 651
550 out of 651
551 out of 651
552 out of 651

553 out of 651
554 out of 651
555 out of 651
556 out of 651
557 out of 651
558 out of 651
559 out of 651
560 out of 651
561 out of 651
562 out of 651
563 out of 651
564 out of 651
565 out of 651
566 out of 651
567 out of 651
568 out of 651
569 out of 651
570 out of 651
571 out of 651
572 out of 651
573 out of 651
574 out of 651
575 out of 651
576 out of 651
577 out of 651
578 out of 651
579 out of 651
580 out of 651
581 out of 651
582 out of 651
583 out of 651
584 out of 651
585 out of 651
586 out of 651
587 out of 651
588 out of 651
589 out of 651
590 out of 651
591 out of 651
592 out of 651
593 out of 651
594 out of 651
595 out of 651
596 out of 651
597 out of 651
598 out of 651
599 out of 651
600 out of 651
601 out of 651
602 out of 651
603 out of 651
604 out of 651
605 out of 651
606 out of 651
607 out of 651
608 out of 651
609 out of 651
610 out of 651
611 out of 651
612 out of 651
613 out of 651
614 out of 651
615 out of 651
616 out of 651
617 out of 651
618 out of 651
619 out of 651
620 out of 651
621 out of 651
622 out of 651
623 out of 651
624 out of 651
625 out of 651
626 out of 651
627 out of 651
628 out of 651
629 out of 651
630 out of 651
631 out of 651
632 out of 651
633 out of 651
634 out of 651
635 out of 651
636 out of 651
637 out of 651
638 out of 651
639 out of 651
640 out of 651
641 out of 651
642 out of 651
643 out of 651
644 out of 651
645 out of 651
646 out of 651
647 out of 651
648 out of 651
649 out of 651
650 out of 651
Sheet Number: 1
Sheet Name: LNBTS
2 out of 644
3 out of 644
4 out of 644
5 out of 644
6 out of 644
7 out of 644
8 out of 644
9 out of 644
10 out of 644
11 out of 644
12 out of 644
13 out of 644
14 out of 644
15 out of 644
16 out of 644
17 out of 644
18 out of 644
19 out of 644
20 out of 644
21 out of 644
22 out of 644
23 out of 644
24 out of 644
25 out of 644
26 out of 644
27 out of 644
28 out of 644
29 out of 644
30 out of 644
31 out of 644
32 out of 644
33 out of 644

KeyboardInterrupt:

In [38]:
df = pd.DataFrame()
for keys in col:
    df = pd.concat((df, col[keys]), axis = 1)
    
df.to_csv('result.csv', index = False)

In [ ]:
# df.append({'a': 2}, ignore_index = True)    
    
#     total_rows = []
#     for j in range(2, sheet.nrows):
#         row=[wb.sheet_names[i]]
#         for k in range(l[i]):
#             row += [sheet.cell_value(j, k)]
#     #         print(row)
#         for k in range(l[i, sheet.ncols):
#             row1 = row + [sheet.cell_value(1, k)] + [sheet.cell_value(j, k)]
#     #         print(row1)
#             total_rows += [row1]
    
    
    
    
    
    
#     columnset = {0, wb.sheet_names()[i]}
#     for j in range(l[i]):
#         temp = sheet.cell_value(1,j)
#         columnset.add[temp]
#         print(temp)
        
#     for j in range(len(columnset)):
#         columns += [columnset.pop()]
#     columns += ['parameter', 'value']
    
#     df = pd.DataFrame(columns = columns)
    
    
    
    
    
    
    
    
# # Import pandas package  
# import pandas as pd 
  
# # Define a dictionary containing Students data 
# data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'], 
#         'Height': [5.1, 6.2, 5.1, 5.2], 
#         'Qualification': ['Msc', 'MA', 'Msc', 'Msc']} 
  
# # Convert the dictionary into DataFrame 
# df = pd.DataFrame(data) 
  
# # Using DataFrame.insert() to add a column 
# df.insert(2, "Age", [21, 23, 24, 21], True) 
  
# # Observe the result 
# df

In [27]:
columns = ['class']
for i in range(5):
    columns += [sheet.cell_value(1, i)]
columns += ['parameter', 'value']

In [28]:
total_rows = []
for i in range(2, sheet.nrows):
    row=['class']
    for j in range(5):
        row += [sheet.cell_value(i, j)]
#         print(row)
    for j in range(5, sheet.ncols):
        row1 = row + [sheet.cell_value(1, j)] + [sheet.cell_value(i, j)]
#         print(row1)
        total_rows += [row1]

In [29]:
# columns
df = pd.DataFrame(total_rows, columns = columns)
df
df.to_csv('out.csv', index = False)

In [32]:
setss = {1, 2,2,3 ,5 ,66,5}

In [34]:
len(setss)

5

In [36]:
setss.pop()

1

In [37]:
setss

{2, 3, 5, 66}

In [40]:
wb.sheet_names()

['MRBTS', 'Sheet1', 'LNBTS', 'LNBTS-2', 'LNBTS-3', 'HW', 'PPTT', 'BTSSCL']

In [55]:
col = ['a']
df = pd.DataFrame(columns = col)

In [4]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [53]:
df = pd.DataFrame()

In [54]:
df

Empty DataFrame
Columns: []
Index: []

In [101]:
for i in range(2,5):
    print(i)

2
3
4

In [9]:
df1 = pd.DataFrame(columns = ['a'])
df2 = pd.DataFrame(columns = ['b'])
df1 = df1.append({'a': 1}, ignore_index = True)
df1 = df1.append({'a': 2}, ignore_index = True)
df2 = df2.append({'b': 3}, ignore_index = True)
df2 = df2.append({'b': 4}, ignore_index = True)

In [11]:
df2

   b
0  3
1  4

In [12]:
df1 = pd.concat((df1, df2), axis = 1)

In [13]:
df1

   a  b
0  1  3
1  2  4